version: '3.9'

networks:
  microservice-network:
    driver: bridge

services:

  prometheus:
    container_name: prometheus
    hostname: prometheus
    build: 
      context: .
      dockerfile: Dockerfile.prometheus.dev
    ports:
      - "9090:9090"
    networks:
      - microservice-network

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    hostname: grafana
    ports:
      - "3001:3000"   
    depends_on:
      - prometheus
    networks:
      - microservice-network

  jaeger:
    image: jaegertracing/all-in-one:1.40
    container_name: jaeger
    hostname: jaeger
    restart: unless-stopped
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 16686:16686
      - 4317:4317
      - 4318:4318
    networks:
      - microservice-network

