version: '3.9'

networks:
  microservice-network:
    name : microservice-network
    driver: bridge

services:

  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    container_name: consul
    ports:
      - "8500:8500"
    networks:
      - microservice-network

  servicesqlserver:
    container_name: servicesqlserver
    hostname: servicesqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${SERVICE_SA_PASSWORD}
      ACCEPT_EULA: "Y"
    networks:
      - microservice-network

  webapigateway:
    container_name: webapigateway
    hostname: webapigateway
    restart: on-failure
    build:
      context: .
      dockerfile: /webapigateway/Dockerfile.apigateway.web.dev
    ports:
      - 14798:80
    depends_on:
      - consul
    environment:
      - ASPNETCORE_ENVIRONMENT=${RUNNING_ENVIRONMENT}            
      - JWTCONFIG__Secret=${JWTCONFIG__Secret}
      - JWTCONFIG__Duration=${JWTCONFIG__Duration}
      - JWTCONFIG__Issuer=${JWTCONFIG__Issuer}
      - JWTCONFIG__Audience=${JWTCONFIG__Audience}
      - JWTCONFIG__RefreshTokenDuration=${JWTCONFIG__RefreshTokenDuration}
      - AUTHENTICATION_PROVIDERKEY=${AUTHENTICATION_PROVIDERKEY}
    networks:
      - microservice-network

  identityservice:
    container_name: identityservice
    hostname: identityservice
    restart: on-failure
    build:
      context: .
      dockerfile: /identityservice/Dockerfile.identityservice.dev
    depends_on:
      - servicesqlserver
      - consul
      - webapigateway
    ports:
      - ${IDENTITYSERVICE_PORT}:80
    environment:
      - ASPNETCORE_ENVIRONMENT=${RUNNING_ENVIRONMENT}            
      - JWTCONFIG__Secret=${JWTCONFIG__Secret}
      - JWTCONFIG__Duration=${JWTCONFIG__Duration}
      - JWTCONFIG__Issuer=${JWTCONFIG__Issuer}
      - JWTCONFIG__Audience=${JWTCONFIG__Audience}
      - JWTCONFIG__RefreshTokenDuration=${JWTCONFIG__RefreshTokenDuration}
      - AUTHENTICATION_PROVIDERKEY=${AUTHENTICATION_PROVIDERKEY}
      - IDENTITY_DEFAULTCONNECTION=${IDENTITY_DEFAULTCONNECTION}
      - CONSULHOSTINFO__ConsulHost=${CONSULHOSTINFO__ConsulHost}
      - CONSULHOSTINFO__ConsulPort=${CONSULHOSTINFO__ConsulPort}
      - CONSULIDENTITYSERVICEINFO__ServiceIp=${CONSULIDENTITYSERVICEINFO__ServiceIp}
      - CONSULIDENTITYSERVICEINFO__ServicePort=${CONSULIDENTITYSERVICEINFO__ServicePort}
      - CONSULIDENTITYSERVICEINFO__ServiceName=${CONSULIDENTITYSERVICEINFO__ServiceName}
    networks:
      - microservice-network

  bookcatalogservice:
    container_name: bookcatalogservice
    hostname: bookcatalogservice
    restart: on-failure
    build:
      context: .
      dockerfile: /bookcatalogservice/Dockerfile.bookcatalogservice.dev
    depends_on:
      - servicesqlserver
      - consul
      - webapigateway
    ports:
      - ${CATALOGSERVICE_PORT}:80
    environment:
      - ASPNETCORE_ENVIRONMENT=${RUNNING_ENVIRONMENT}            
      - JWTCONFIG__Secret=${JWTCONFIG__Secret}
      - JWTCONFIG__Duration=${JWTCONFIG__Duration}
      - JWTCONFIG__Issuer=${JWTCONFIG__Issuer}
      - JWTCONFIG__Audience=${JWTCONFIG__Audience}
      - JWTCONFIG__RefreshTokenDuration=${JWTCONFIG__RefreshTokenDuration}
      - AUTHENTICATION_PROVIDERKEY=${AUTHENTICATION_PROVIDERKEY}
      - CATALOG_DEFAULTCONNECTION=${CATALOG_DEFAULTCONNECTION}
      - CONSULHOSTINFO__ConsulHost=${CONSULHOSTINFO__ConsulHost}
      - CONSULHOSTINFO__ConsulPort=${CONSULHOSTINFO__ConsulPort}
      - CONSULCATALOGSERVICEINFO__ServiceIp=${CONSULCATALOGSERVICEINFO__ServiceIp}
      - CONSULCATALOGSERVICEINFO__ServicePort=${CONSULCATALOGSERVICEINFO__ServicePort}
      - CONSULCATALOGSERVICEINFO__ServiceName=${CONSULCATALOGSERVICEINFO__ServiceName}
    networks:
      - microservice-network

  reviewservice:
    container_name: reviewservice
    hostname: reviewservice
    restart: on-failure
    build:
      context: .
      dockerfile: /reviewservice/Dockerfile.reviewservice.dev
    depends_on:
      - servicesqlserver
      - consul
      - webapigateway
    ports:
      - ${REVIEWSERVICE_PORT}:80
    environment:
      - ASPNETCORE_ENVIRONMENT=${RUNNING_ENVIRONMENT}            
      - JWTCONFIG__Secret=${JWTCONFIG__Secret}
      - JWTCONFIG__Duration=${JWTCONFIG__Duration}
      - JWTCONFIG__Issuer=${JWTCONFIG__Issuer}
      - JWTCONFIG__Audience=${JWTCONFIG__Audience}
      - JWTCONFIG__RefreshTokenDuration=${JWTCONFIG__RefreshTokenDuration}
      - AUTHENTICATION_PROVIDERKEY=${AUTHENTICATION_PROVIDERKEY}
      - REVIEW_DEFAULTCONNECTION=${REVIEW_DEFAULTCONNECTION}
      - CONSULHOSTINFO__ConsulHost=${CONSULHOSTINFO__ConsulHost}
      - CONSULHOSTINFO__ConsulPort=${CONSULHOSTINFO__ConsulPort}
      - CONSULREVIEWSERVICEINFO__ServiceIp=${CONSULREVIEWSERVICEINFO__ServiceIp}
      - CONSULREVIEWSERVICEINFO__ServicePort=${CONSULREVIEWSERVICEINFO__ServicePort}
      - CONSULREVIEWSERVICEINFO__ServiceName=${CONSULREVIEWSERVICEINFO__ServiceName}
    networks:
      - microservice-network


