version: '3.9'

services:

  identitysqlserver:
    container_name: identitysqlserver
    hostname: identitysqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${IDENTITY_SA_PASSWORD}
      ACCEPT_EULA: "Y"

  consulserver:
    image: hashicorp/consul:1.10.0
    container_name: consulserver
    hostname: consulserver
    restart: always
    volumes:
     - ./server.json:/consul/config/server.json:ro
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"

  consulclient:
    image: hashicorp/consul:1.10.0
    container_name: consulclient
    hostname: consulclient
    restart: always
    volumes:
     - ./client.json:/consul/config/client.json:ro
    command: "agent"

  webapigateway:
    container_name: webapigateway
    hostname: webapigateway
    build:
      context: .
      dockerfile: /webapigateway/Dockerfile.apigateway.web.dev
    ports:
      - 14798:80
    links:
      - consulclient
      - consulserver
    depends_on:
      - consulclient
      - consulserver
    environment:
      - ASPNETCORE_ENVIRONMENT=${RUNNING_ENVIRONMENT}            
      - JWTCONFIG__Secret=${JWTCONFIG__Secret}
      - JWTCONFIG__Duration=${JWTCONFIG__Duration}
      - JWTCONFIG__Issuer=${JWTCONFIG__Issuer}
      - JWTCONFIG__Audience=${JWTCONFIG__Audience}
      - JWTCONFIG__RefreshTokenDuration=${JWTCONFIG__RefreshTokenDuration}
      - AUTHENTICATION_PROVIDERKEY=${AUTHENTICATION_PROVIDERKEY}