global:
  scrape_interval: 15s
  scrape_timeout: 5s

rule_files:

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: identityservice
    static_configs:
      - targets: ["identityservice"]

  - job_name: bookcatalogservice
    static_configs:
      - targets: ["bookcatalogservice"]