FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["webapigateway/webapigateway.csproj", "webapigateway/"]
COPY ["sharedkernel/sharedkernel.csproj", "sharedkernel/"]
COPY ["sharedsecurity/sharedsecurity.csproj", "sharedsecurity/"]
COPY ["sharedmonitoring/sharedmonitoring.csproj", "sharedmonitoring/"]
RUN dotnet restore "webapigateway/webapigateway.csproj"
COPY . .
WORKDIR "/src/webapigateway"
RUN dotnet build "webapigateway.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "webapigateway.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "webapigateway.dll"]
