FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["shelveservice/shelveservice.csproj", "shelveservice/"]
COPY ["sharedkernel/sharedkernel.csproj", "sharedkernel/"]
COPY ["sharedsecurity/sharedsecurity.csproj", "sharedsecurity/"]
COPY ["sharedmonitoring/sharedmonitoring.csproj", "sharedmonitoring/"]
RUN dotnet restore "shelveservice/shelveservice.csproj"
COPY . .
WORKDIR "/src/shelveservice"
RUN dotnet build "shelveservice.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "shelveservice.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "shelveservice.dll"]