#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["reviewservice/reviewservice.csproj", "reviewservice/"]
COPY ["sharedkernel/sharedkernel.csproj", "sharedkernel/"]
COPY ["sharedsecurity/sharedsecurity.csproj", "sharedsecurity/"]
RUN dotnet restore "reviewservice/reviewservice.csproj"
COPY . .
WORKDIR "/src/reviewservice"
RUN dotnet build "reviewservice.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "reviewservice.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "reviewservice.dll"]