FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["bookcatalogservice/bookcatalogservice.csproj", "bookcatalogservice/"]
COPY ["sharedkernel/sharedkernel.csproj", "sharedkernel/"]
COPY ["sharedsecurity/sharedsecurity.csproj", "sharedsecurity/"]
COPY ["sharedmonitoring/sharedmonitoring.csproj", "sharedmonitoring/"]
RUN dotnet restore "bookcatalogservice/bookcatalogservice.csproj"
COPY . .
WORKDIR "/src/bookcatalogservice"
RUN dotnet build "bookcatalogservice.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "bookcatalogservice.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "bookcatalogservice.dll"]